[flake8]
max-line-length=120
max-complexity=15
ignore=B023, DJ01, W503, W504, B902, N818
ignore-names=setUp, setUpClass, setUpTestData, tearDown
exclude =
    __pycache__,
    .git,
    .static,
    manage.py,
    *migrations*,
    *node_modules*,

[isort]
default_section=THIRDPARTY
include_trailing_comma=true
known_first_party=mwk
line_length=120
multi_line_output=3
skip=migrations, settings

[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py40']
single-quotes = true
