# Generated by Django 4.2a1 on 2023-04-18 20:42

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'user_from',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='from_set',
                        to='authentication.profile',
                        verbose_name='From',
                    ),
                ),
                (
                    'user_to',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='to_set',
                        to='authentication.profile',
                        verbose_name='To',
                    ),
                ),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True,
                     db_index=True,
                     verbose_name='Created at'
                 )),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('user_from', django.db.models.expressions.F('user_to'))
                ),
                name='check_self_follow',
            ),
        ),
    ]
