# Generated by Django 4.2a1 on 2023-04-16 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_create_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title', models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name='Post Title'
                    )
                ),
                (
                    'content',
                    models.TextField(
                        blank=True,
                        verbose_name='Post Text'
                    )
                ),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Author',
                    ),
                ),
                (
                    'liked',
                    models.ManyToManyField(
                        blank=True,
                        related_name='liked_posts',
                        related_query_name='liked_posts',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Liked By',
                    ),
                ),
                (
                    'viewers',
                    models.ManyToManyField(
                        blank=True,
                        related_name='viewed_posts',
                        related_query_name='viewed_posts',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Viewers',
                    ),
                ),
                (
                    'profile',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='posts',
                        related_query_name='posts',
                        to='authentication.profile',
                        verbose_name='Profile',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Last updated'),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
                ),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
