# Generated by Django 4.2a1 on 2023-04-16 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import mwk.modules.main.helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name='Created'
                    )
                ),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Author',
                    ),
                ),
                (
                    'photo',
                    models.ImageField(
                        upload_to=mwk.modules.main.helpers.helpers.PathAndRenameDate(
                            'photos/posts/'
                            ),
                        verbose_name='Photo',
                    ),
                ),
                (
                    'post',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        related_query_name='images',
                        to='main.post',
                        verbose_name='Post',
                    ),
                ),
            ],
            options={
                'ordering': ('created_at',),
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
