# Generated by Django 4.2a1 on 2023-04-18 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_followers_field_to_profile'),
        ('main', '0003_create_comment'),
    ]
    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=50, verbose_name='Category Name'),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Created at'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Category of post',
                'verbose_name_plural': 'Categories of posts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts',
                related_query_name='posts',
                to='main.postcategory',
                verbose_name='Category',
            ),
        ),
    ]

